wandb_version: 1

batch_size:
  desc: null
  value: 64
lr:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 60
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1710014912.445776
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.16.3
      8:
      - 1
      - 2
      - 3
      - 5
      13: windows-amd64
