wandb_version: 1

batch_size:
  desc: null
  value: 256
num_epochs:
  desc: null
  value: 10
init_lr:
  desc: null
  value: 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1713046560.45495
    t:
      1:
      - 1
      - 55
      - 95
      2:
      - 1
      - 55
      - 95
      3:
      - 2
      - 3
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.16.3
      8:
      - 1
      - 2
      - 3
      - 5
      13: windows-amd64
